WORLD_SIZE=${WORLD_SIZE:-1}
RANK=${RANK:-0}
MASTER_ADDR=${MASTER_ADDR:-127.0.0.1}
MASTER_PORT=${MASTER_PORT:-23458}
NGPUS="4"

export CUDA_VISIBLE_DEVICES="0,1,2,3"
# Dual-arm sim dataset generated by tools/pickle_gen/pickle_generation_sim.py
DATAPATH='/remote-home/linweihao/maniparena_dataset_sim/processed_data/meta/sim_all_dualarm_norm.pkl'
ACTION_TOKENIZER_PATH="/remote-home/linweihao/structvla/pretrain/fast"
EXP_NAME="SIM__500"
export NCCL_IGNORE_DISABLED_P2P=1
export PYTHONPATH=$(pwd)
export WANDB_MODE=offline

# Local log directory; keep it consistent with your output_dir
export WANDB_DIR="logs/${EXP_NAME}/wandb"

# Optional: project name and run name
export WANDB_PROJECT="structvla"
export WANDB_RUN_GROUP="${EXP_NAME}"
torchrun \
    --nproc_per_node=${NGPUS} \
    --nnodes=1 \
    --node_rank=${RANK} \
    --master_addr=${MASTER_ADDR} \
    --master_port=${MASTER_PORT} \
    train/train_moe.py \
    --model_name_or_path /remote-home/linweihao/structvla/logs/ManipArena_sim/merged \
    --model_config_path /remote-home/linweihao/structvla/configs/moe_fast_video.json \
    --deepspeed scripts/sft/zero3.json \
    --output_dir "logs/"${EXP_NAME} \
    --learning_rate 5e-5 \
    --null_prompt_prob 0.15 \
    --weight_decay 0.1 \
    --min_learning_rate 5e-6 \
    --max_grad_norm 5.0 \
    --adam_beta1 0.9 \
    --adam_beta2 0.95 \
    --adam_epsilon 1e-6 \
    --bf16 True \
    --tf32 True \
    --data_path ${DATAPATH} \
    --max_steps 500 \
    --dataloader_num_workers 16 \
    --lr_scheduler_type "cosine_with_min_lr" \
    --warmup_steps 10 \
    --per_device_train_batch_size 2 \
    --frames 2\
    --action_frames 20 \
    --max_position_embeddings 5500 \
    --seed 42 \
    --logging_steps 20 \
    --gradient_checkpointing True \
    --gradient_accumulation_steps 4 \
    --save_strategy steps \
    --save_steps 300 \
    --eval_strategy no \
    --apply_loss_on_only_vision True \
    --apply_loss_on_only_action True \
    --actions True \
    --actions_format "fast" \
    --use_gripper True \
    --video_format "interleave" \
    --real_robot True \
    --action_tokenizer_path ${ACTION_TOKENIZER_PATH} \
    --report_to "wandb" \
    --run_name ${EXP_NAME} \
    > /remote-home/linweihao/structvla/sim_dualarm.log 2>&1
